"""add_archived_to_documents

Revision ID: 8bfee017ff4c
Revises: 8f4f76a642f4
Create Date: 2026-05-17 21:32:47.175053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bfee017ff4c'
down_revision: Union[str, None] = '8f4f76a642f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'archived')
    # ### end Alembic commands ###
